server:
  port: 8010

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/utkryuk/config-server
          default-label: main
          clone-on-start: true